- name: installnginx
  hosts: web
  become: yes
  tasks:
   - name: installingnginx
     ansible.builtin.package:
      name: nginx
      state: present
   - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started